import Head from 'next/head';
import Navbar from './navbar';

export default function Layout({ children }) {
  return (
    <div>
      <Head>
      <title>TAKA</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
      <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
    </Head>
      <Navbar />
      <div className='page-content'>
        {children}
      </div>
    </div>
  )
}
